### ISSUE TITLE
Documentação

### ISSUE THREAD

**Issue by RafaelRSPX** [RafaelRSPX/arvoremestre#1]
Pessoal, chequem a documentação do programa. Adicionem seus e-mails e se possível melhorem do README.md.

**Comment by RafaelRSPX** [comment]
Adicionem seus nomes no AUTHORS

**Comment by flavioduart** [comment]
Adicionado!

**Comment by guidoferrario** [comment]
Adicionado.

**Comment by eilins** [comment]
Adicionado!

**Comment by flavioduart** [comment]
Melhorei o README :dancer:

**Comment by caahreginaa** [comment]
Adicionado!
