### ISSUE TITLE
Comentários e indentação

### ISSUE THREAD

**Issue by eilins** [RafaelRSPX/arvoremestre#10]
Comentem mais o código para facilitar o entendimento e observem a indentação.

**Comment by guidoferrario** [comment]
Fiz correções na indentação e acredito que melhorei um pouco da organização.

**Comment by caahreginaa** [comment]
Ótimo. Vai testando o programa para ver se tem algum bug. Tens testado?

**Comment by RafaelRSPX** [comment]
Realizei alguns testes e nada de anormal aconteceu. Além disso, fiz algumas modificações no código, como remoção da função preord e de linhas inúteis e remoção de printf com DEBUG.
