### ISSUE TITLE
Esquerda e direita

### ISSUE THREAD

**Issue by RafaelRSPX** [RafaelRSPX/arvoremestre#3]
O ponteiro da árvore vai para a esquerda quando o usuário digita sim ou não?

**Comment by flavioduart** [comment]
Se eu não me engane, ele vai para esquerda quando recebe "não"

**Comment by caahreginaa** [comment]
No exemplo que ruben fez em sala, a esquerda era não, mas ele mandou fazermos o contrário, então creio que no nosso programa a esquerda será sim e a direita não.

**Comment by flavioduart** [comment]
Ele mandou fazer o contrário apenas em uma folha na sala de aula para visualizar como ficava ou no nosso programa também? :question:

**Comment by guidoferrario** [comment]
Lembro que no exemplo feito em aula, a esquerda era não.

**Comment by RafaelRSPX** [comment]
Esquerda para não?

**Comment by flavioduart** [comment]
Na sala foi assim. Mas como Cassia falou, ele mandou fazer o contrário, só não me recordo se foi para fazer o contrário apenas em um papel ou se era para fazer o contrário no programa

**Comment by RafaelRSPX** [comment]
Acredito que era no papel.

**Comment by caahreginaa** [comment]
Não vai mudar significativamente no programa, acho que tanto faz se a direita for pra sim ou não

**Comment by RafaelRSPX** [comment]
Deixei esquerda para sim e direita para não. Commit: 280645ad3a504008bebc1f0ca85195c425089758
