### ISSUE TITLE
Função para passar o arquivo para memória

### ISSUE THREAD

**Issue by RafaelRSPX** [RafaelRSPX/arvoremestre#4]
Caros, gostaria de uma função para passar o arquivo animal.txt para a árvore. Além disso, nós devemos criar um arquivo inicial manualmente com informações básicas?

**Comment by flavioduart** [comment]
Creio que o arquivo inicial seria interessante

**Comment by caahreginaa** [comment]
Devemos sim e ja estou trabalhando nessa função para passar o arquivo pra arvore

**Comment by RafaelRSPX** [comment]
Quem poderia criar um arquivo bem simples, seguindo a impressão em preord?

**Comment by RafaelRSPX** [comment]
Tentarei implementar a inserção de nova informação na árvore.

**Comment by caahreginaa** [comment]
Adicionei esta função no commit 7cfb6b5adc290ea0594ddc9bac623d750a405f5e
