### ISSUE TITLE
Função preord

### ISSUE THREAD

**Issue by caahreginaa** [RafaelRSPX/arvoremestre#5]
Pessoal, estou editando a função preord porque no momento ela esta com a mesma utilidade da função graaarq. Sugiro que deixemos a preord apenas para lermos a arvore e gravemos as informações no arquivo com outra função.

**Comment by RafaelRSPX** [comment]
Tudo bem.

**Comment by RafaelRSPX** [comment]
Fiz uma modificação na função preord para imprimir no arquivo banco_de_dados.txt a árvore na forma preord.

**Comment by caahreginaa** [comment]
Eu disse pra deixar a preord pra leitura e criava outra função pra salvar o arquivo....

**Comment by RafaelRSPX** [comment]
Mas tá sem uso mesmo. Pode modificar. Eh que eu tinha feito uma preord antes de abrir essa issue.

**Comment by caahreginaa** [comment]
Eu tinha criado outra função le arquivo, mas dps que vi o que comentasse aqui, apaguei e modifiquei a preord pra imprimir a arvore.
