### ISSUE TITLE
Função lebanco 

### ISSUE THREAD

**Issue by RafaelRSPX** [RafaelRSPX/arvoremestre#6]
Pessoal fiz alguns testes com o novo banco de dados e a função lebanco não aceita linhas com duas palavras. Ele fica num laço infinito quando atinge uma linha com mais de uma palavra, por exemplo, a linha pesa toneladas.

**Comment by flavioduart** [comment]
Entao a gente determina que só vai ser possível utilizar uma palavra? Acho melhor tentar ajeitar a função

**Comment by caahreginaa** [comment]
Achei uma forma de resolver o problema, vou testar agora

**Comment by caahreginaa** [comment]
Fiz a alteração e já enviei. Só que acho que tinham modificado o arquivo do bando de dados, porque no momento só tem "pesa" e não pesa toneladas. Mas coloquei pesa toneladas e funcionou o teste

**Comment by RafaelRSPX** [comment]
Isso mesmo. Tinha tirado o toneladas e chifre para fazer alguns testes.

**Comment by caahreginaa** [comment]
Pode adicionar toneladas e chifre no banco de novo, porque eu so modifiquei pra testar mesmo, mas nao enviei.

**Comment by guidoferrario** [comment]
Modifiquei, adicionei "toneladas" e "chifre".
