### ISSUE TITLE
Laço para as perguntas

### ISSUE THREAD

**Issue by RafaelRSPX** [RafaelRSPX/arvoremestre#7]
Implementei o laço para repetição das perguntas ou respostas para parar quando chegar na folha (esq e dir == NULL). Mas o programa finaliza na primeira pergunta quando responde n na primeira pergunta. O que vcs sugerem como condição para o laço das perguntas e repostas?

**Comment by caahreginaa** [comment]
Testei agora e colocando não ele só foi finalizar depois de rasteja. Mas mesmo assim ainda ficou faltando coisas

**Comment by RafaelRSPX** [comment]
Isso.

**Comment by flavioduart** [comment]
:eyes:

**Comment by eilins** [comment]
Acredito que resolvi o problema :facepunch:
