### ISSUE TITLE
Reunião

### ISSUE THREAD

**Issue by RafaelRSPX** [RafaelRSPX/arvoremestre#8]
Amanhã durante a aula de expressão em língua portuguesa vocês estarão livres (já que vai se segunda chamada)? Gostaria de conversar sobre alguns pontos do programa. São pontos que são necessários vcs estarem presentes.

**Comment by flavioduart** [comment]
Estou livre sim!

**Comment by RafaelRSPX** [comment]
Se possível, vocês podem trazer um notebook?

**Comment by guidoferrario** [comment]
Estou livre e posso levar o notebook!

**Comment by eilins** [comment]
Todos presentes e pontos discutidos.
